apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "acme-gateway.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "acme-gateway.labels" . | nindent 4 }}
data:
  config.yaml: |
{{ include "acme-gateway.configYaml" . | indent 4 }}
{{ if .Values.dnsHooks.enabled -}}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "acme-gateway.fullname" . }}-dns-hooks
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "acme-gateway.labels" . | nindent 4 }}
data:
  deploy-dns.sh: |
{{ .Values.dnsHooks.deployScript | indent 4 }}
  cleanup-dns.sh: |
{{ .Values.dnsHooks.cleanupScript | indent 4 }}
{{- end }}
