apiVersion: v1
kind: Service
metadata:
  name: {{ include "acme-gateway.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "acme-gateway.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: {{ if .Values.config.server.tls }}https{{ else }}http{{ end }}
      port: {{ .Values.service.port }}
      targetPort: {{ if .Values.config.server.tls }}https{{ else }}http{{ end }}
      protocol: TCP
  selector:
    {{- include "acme-gateway.selectorLabels" . | nindent 4 }}
